# Generated by Django 6.0 on 2026-04-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('chunk_hash', models.CharField(db_index=True, max_length=64)),
                ('page_content_hash', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('section', models.CharField(blank=True, max_length=256)),
                ('source_type', models.CharField(choices=[('main_site', 'Main Site'), ('obs', 'OBS')], db_index=True, max_length=16)),
                ('url', models.URLField(db_index=True, max_length=1024)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('token_count_estimate', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraped_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chatbot.scrapedpage')),
            ],
            options={
                'ordering': ('scraped_page_id', 'chunk_index'),
                'indexes': [models.Index(fields=['source_type', 'section'], name='chatbot_pag_source__bf1c29_idx'), models.Index(fields=['url'], name='chatbot_pag_url_a3e327_idx')],
                'constraints': [models.UniqueConstraint(fields=('scraped_page', 'chunk_index'), name='uniq_page_chunk_index'), models.UniqueConstraint(fields=('scraped_page', 'chunk_hash'), name='uniq_page_chunk_hash')],
            },
        ),
    ]
