# Generated by Django 6.0 on 2026-04-06 15:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_pagechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagechunk',
            name='embedded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pagechunk',
            name='embedded_chunk_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pagechunk',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pagechunk',
            name='embedding_dim',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagechunk',
            name='embedding_model',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
