# Generated by Django 6.0 on 2026-04-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chunkembedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagechunk',
            name='embedded_at',
        ),
        migrations.RemoveField(
            model_name='pagechunk',
            name='embedded_chunk_hash',
        ),
        migrations.RemoveField(
            model_name='pagechunk',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='pagechunk',
            name='embedding_dim',
        ),
        migrations.RemoveField(
            model_name='pagechunk',
            name='embedding_model',
        ),
    ]
