# Generated by Django 6.0 on 2026-04-23 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_pagechunk_embedded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('embedding_model', models.CharField(default='sentence-transformers/all-MiniLM-L6-v2', max_length=255)),
                ('embedding_dim', models.PositiveIntegerField()),
                ('chunk_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_data', to='chatbot.pagechunk')),
            ],
        ),
    ]
