# Generated by Django 5.2.13 on 2026-04-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_scrapedpage_url_variant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chatbot_mes_convers_b353f0_idx',
            old_name='chatbot_mes_conv_created_idx',
        ),
    ]
