# Generated by Django 5.2.13 on 2026-05-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_add_metadata_jsonfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkembedding',
            name='embedding_model',
            field=models.CharField(default='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2', max_length=255),
        ),
    ]
